<?php
// Autogenerated extension filesystems
// This config is merged with config/filesystems.php

return [
  'disks' => [
    /* blueprint/disks *//* ServerlockStart */ 'blueprint:serverlock' => [ 'driver' => 'local', 'root' => storage_path('extensions/serverlock'), 'url' => env('APP_URL') . '/fs/extensions/serverlock', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:serverlock' => [ 'driver' => 'local', 'root' => storage_path('.extensions/serverlock'), 'throw' => false, ], /* ServerlockEnd *//* CrimsonabyssStart */ 'blueprint:crimsonabyss' => [ 'driver' => 'local', 'root' => storage_path('extensions/crimsonabyss'), 'url' => env('APP_URL') . '/fs/extensions/crimsonabyss', 'visibility' => 'public', 'throw' => false, ], 'blueprint_private:crimsonabyss' => [ 'driver' => 'local', 'root' => storage_path('.extensions/crimsonabyss'), 'throw' => false, ], /* CrimsonabyssEnd */
  ],
];
